[phases.setup]
cmds = ["cd Server && go mod download && cd ../Client && npm install"]

[phases.build]
cmds = ["cd Server && go build -o main && cd ../Client && npm run build"]

[start]
cmd = "cd Server && ./main"