[phases.setup]
cmds = [
    "cd Server && go mod download",
    "cd ../Client && npm install"
]

[phases.build]
cmds = [
    "cd Server && CGO_ENABLED=0 GOOS=linux go build -o ../out",
    "cd ../Client && npm run build"
]

[start]
cmd = "./out"