[phases]

  # Phase untuk build Client (React)
  [phases.client-install]
  description = "Install dependencies for the client"
  run = "npm install --prefix ./Client"

  [phases.client-build]
  description = "Build the client app"
  run = "npm run build --prefix ./Client"

  # Phase untuk build Server (Go)
  [phases.server-install]
  description = "Install dependencies for the server"
  run = "go mod download"
  
  [phases.server-build]
  description = "Build the server"
  run = "go build -o server ./Server"

[run]

  # Jalankan server dengan output binary yang sudah di-build
  start = "./server"
